### ISSUE TITLE
Broken WIFI after reboot

### ISSUE THREAD

**Issue by fgutierrezz** [OpenMediaVault-Plugin-Developers/docs#10]
I also created a comment in the forums 
> https://www.raspberrypi.org/forums/viewtopic.php?f=91&t=263424
> https://forum.openmediavault.org/index.php?thread/31616-omv-breaks-my-network-wifi-static-configuration-after-installation/

Raspbery PI 3 B 

* If using WIFI Static in rpi 3 , after installing omv using steps in page 16 of document "Adden-B-installing_OMV5_on_an_R-PI.pdf" after reboot the network configuration (static ip with wifi ) is broken and no able to configure the network again. 

* To fix this, after the script is completed DONT REBOOT by any reason. 
* open the GUI Login and immediately change and set the WIFI settings there, apply and save changes. 
* Now you can perform the reboot and OMV will work with network configured. 

![Screenshot from 2020-03-23 22-58-17](https://user-images.githubusercontent.com/30966360/77380518-09f8b580-6d5a-11ea-9f0c-f3df7b24f1e7.png)

**Comment by Djerbiien** [comment]
same problem with PI 4

**Comment by flmaxey** [comment]
The decision was made to depreciate NetworkManager, on SBC's.  There were two reasons for this decision:
- Supporting Portainer, to allow for easy use of Dockers, was a priority add-on for OMV5.  NetworkManager wreaks networking for Portainer and Dockers.  
- A NAS is a traditional file server.  As a matter of good practice, even in home environments, a file server should be running on a wired connection.  Practically speaking, the bottleneck created by wireless creates other problems when streaming Video content.

In accordance with the above, the install script removes Network Manager.  Note that if Network Manager is manually reinstalled, the script will remove it again, as a matter of course, when it runs.
______________________________________________________________

Accordingly, in the doc's, I'm going to mark the topic "wireless networking" as not supported by default.
