### ISSUE TITLE
Failed to install OMV 

### ISSUE THREAD

**Issue by bigyo** [OpenMediaVault-Plugin-Developers/docs#11]
Hi,
I failed to install OMV to Armbian Bionic Linux 5.4.35-sunxi

I got the following error, could you help what could be the issue?
Thx.

root@bananapi:~# sudo wget -O - https://github.com/OpenMediaVault-Plugin-Developers/packages/raw/master/install | bash
--2020-05-01 20:42:35--  https://github.com/OpenMediaVault-Plugin-Developers/packages/raw/master/install
Resolving github.com (github.com)... 140.82.118.4
Connecting to github.com (github.com)|140.82.118.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/OpenMediaVault-Plugin-Developers/packages/master/install [following]
--2020-05-01 20:42:35--  https://raw.githubusercontent.com/OpenMediaVault-Plugin-Developers/packages/master/install
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1067 (1.0K) [text/plain]
Saving to: ‘STDOUT’

-                                                           100%[========================================================================================================================================>]   1.04K  --.-KB/s    in 0s

2020-05-01 20:42:35 (4.70 MB/s) - written to stdout [1067/1067]

dpkg-query: no packages found matching openmediavault
0
Unsupported version of openmediavault

**Comment by ryecoaaron** [comment]
See the unsupported line in the output? OMV only works on Debian.
