### ISSUE TITLE
Add 'Enable predictable network interface name' in Raspberry install guide

### ISSUE THREAD

**Issue by VFansss** [OpenMediaVault-Plugin-Developers/docs#12]
Hi!

I've followed the .pdf guide to [install OMV on a Rasp Pi4](https://github.com/OpenMediaVault-Plugin-Developers/docs/blob/master/Adden-B-Installing_OMV5_on_an%20R-PI.pdf) and has served me very well. Almost.

I don't know if is because I've used a Raspbian Desktop installation (I've used Raspbian Buster with desktop RELEASE DATE 2020-02-13) and maybe what I'm going to write isn't needed on Raspbian Lite, but when is time to add the Ethernet interface from OMV Dashboard I got a blocking error that prevents me to add the inteface.

After a while, I've found that you have to "Enable predictable network interface name" from raspi config 

* sudo raspi-config
* 'Network option' -> 'N3 Network Interface names' -> Answer 'Yes'
* Reboot

I know that this probably isn't needed if anyone follow strictly the guide, but is a notion that IMHO can improve the guide for those (like me) that want to have a full desktop installation :)

**Comment by flmaxey** [comment]
First, while the R-PI4 is a capable SBC, using it in a file server role AND as a desktop is not good practice.

The desktop version is not supported and there's a specific mention of that in the doc.  Accordingly, if you're looking for a stable NAS, I'd suggest rebuilding with the recommended version.

You may have found a workaround for the interface name issue, however, there are a number of elective software additions for the Desktop version that may result in breaking OMV, to a complete  _uninstallation / removal_ of OMV to resolve a conflict.

If you leave the Desktop version installed, I'd highly recommend that you clone your SD-card while your NAS is working, as an insurance policy against these potential events.  
(How to clone your SD-card is a subject covered in the standard users guide.)

**Comment by ryecoaaron** [comment]
The install script purposely disables predictive naming which is the default of Raspbian.

**Comment by Mikeinnc** [comment]
Thanks for all your hard work! I've used the script to install OMV on a Raspberry Pi3+ and I note that there are a lot of 'warnings' that appear whilst the script is running. They mostly seem to be of the type 'warning: xxxx is deprecated since Python 3.5. Use 'signature' and the 'Signature' object directly *salt.utils.args.get_function_argspec(original_function)' Should I be worried about these? Are they significant - or can they be ignored? Many thanks for your advice!

**Comment by VFansss** [comment]
Sorry for the....long response time.
 
> First, while the R-PI4 is a capable SBC, using it in a file server role AND as a desktop is not good practice.

Yes, I know this!

But at least in my case...it was intented: with the recent Pi4 4GB, I tought that it was good enough to handle a medium desktop and server tasks. 

Is working good, however. At least at present day.

> The desktop version is not supported and there's a specific mention of that in the doc. Accordingly, if you're looking for a stable NAS, I'd suggest rebuilding with the recommended version. You may have found a workaround for the interface name issue, however, there are a number of elective software additions for the Desktop version that may result in breaking OMV, to a complete uninstallation / removal of OMV to resolve a conflict.

Didn't know that.

I anticipated from the beginning that probably was my fault to install such software on a desktop oriented distro build but I tought it worth the hassle to note that.

Even if not, at least for other "adventurer" (or fool) like me, this Issue could pinpoint to the right solution if someone has the same issue.

Thans for your time, and keep up the good work!
