### ISSUE TITLE
Warnings in script run?

### ISSUE THREAD

**Issue by Mikeinnc** [OpenMediaVault-Plugin-Developers/docs#13]
Thanks for all your hard work! I've used the script to install OMV on a Raspberry Pi3+ and I note that there are a lot of 'warnings' that appear whilst the script is running. They mostly seem to be of the type 'warning: xxxx is deprecated since Python 3.5. Use 'signature' and the 'Signature' object directly *salt.utils.args.get_function_argspec(original_function)' Should I be worried about these? Are they significant - or can they be ignored? Many thanks for your advice!

**Comment by flmaxey** [comment]
The Python warnings can be ignored.  The SALT error appears to be a call for _specification_ (spec) for an argument.  As it appears that particular argument is not necessary for your SBC (the R-PI3+).

If you have a working install, enjoy.

**Comment by Mikeinnc** [comment]
Thanks so much for that! Yes, I do have an excellent working system. and
I'll sleep a lot easier knowing I don't need to be concerned about those
warnings.....

**Comment by rxmas** [comment]
The install failed for me. Is there a log I can send?

Brand new RPI 4 4gb model, 4 brand new Seagate hybrid 1tb drives,  Buster lite 09262019 version.

**Comment by flmaxey** [comment]
"Failed" lacks a certain number of details needed. 

Please set up an account at 
**https://forum.openmediavault.org/**
and post the issue there.

Putty is capable of capturing the output of the script, to a text file.  (Look at Putty's options for capturing Putty's terminal data.)  In your post on the forum, attach the file.
____________________________________________________________

Setting the above aside:
While there's nothing to go on in this case, depending on where you are in the world, problems with Raspbian mirror servers in some regions have been noted recently.  (Russia and Canada, for examples.)  If there's a problem with a Raspbian mirror, there's nothing that can be done about it.  (You might see indications in the script output.)  

The easiest approach might be waiting until Monday afternoon (in your time zone) and trying again.  

I noted that you have 4 drives which indicates there's a USB drive dock or enclosure involved.  When you build, the dock / enclosure should be disconnected.
