### ISSUE TITLE
Connection refused.

### ISSUE THREAD

**Issue by baoxiaowei879** [OpenMediaVault-Plugin-Developers/docs#14]
what should i do? rookie here.  thanks 

wget -O - https://github.com/OpenMediaVault-Plugin-Developers/installScript/raw/master/install | sudo bash
--2020-07-14 17:55:22--  https://github.com/OpenMediaVault-Plugin-Developers/installScript/raw/master/install
Resolving github.com (github.com)... 13.229.188.59
Connecting to github.com (github.com)|13.229.188.59|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/OpenMediaVault-Plugin-Developers/installScript/master/install [following]
--2020-07-14 17:55:24--  https://raw.githubusercontent.com/OpenMediaVault-Plugin-Developers/installScript/master/install
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 0.0.0.0, ::
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|0.0.0.0|:443... failed: Connection refused.
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|::|:443... failed: Connection refused.

**Comment by ryecoaaron** [comment]
Your network is blocking the connection.  nothing anyone else can do to fix that.

**Comment by baoxiaowei879** [comment]
> Your network is blocking the connection. nothing anyone else can do to fix that.

Is that because i'm in China? need to connect through VPN?
