### ISSUE TITLE
Minor bug in the PDF

### ISSUE THREAD

**Issue by marcdraco** [OpenMediaVault-Plugin-Developers/docs#15]
The doc (I'm installing on Armbian Buster) continually refers to Raspberry PI which isn't a big deal but ... I don't think Armbian is available for the RPI, DietPi would be a better choice I suspect. 

However the install script is an image (?) so you can't copy/paste it into a terminal. 

This would be an excellent addition to DietPi in fact, perhaps you could suggest it? They're probably sick of me by now! :)

**Comment by ryecoaaron** [comment]
The process is pretty much the same for Raspbian and Armbian.  And you are correct, Armbian is not available for the RPi.  I only test the install script against Raspbian Buster Lite and Armbian (never used Diet Pi).  If it works with Diet Pi, great but I'm not planning to start testing against it.

As for the install script image, what page is that on?  The install script and wget command is always available from the repo if you can't cut&paste from the doc - https://github.com/OpenMediaVault-Plugin-Developers/installScript

**Comment by marcdraco** [comment]
Top man! It's on Page 14 - I expect it's to do with the PDF conversion. I'll admit to being rather delighted I can run OMV on the Lime 2, thanks to you guys and the Armbian developers. I can't thank you all enough.

**Comment by ryecoaaron** [comment]
Ah, when using the github pdf renderer, it is an image.  But when I downloaded the pdf and opened it, I was able to copy the link.

**Comment by flmaxey** [comment]
The source document was the for the R-PI.  You caught a couple items I missed, referencing the R-PI in the donation and post install section.  (I have no proof readers and very few comment as you did.)  

R-PI ref's have been purged or corrected.

Thanks for the catch.

**Comment by marcdraco** [comment]
No worries, I'm very glad to have you make such clear instructions! Install went without a hitch, now I just need to add a few tb of store and we're "cookin' on gas"  as we say here in Blighty!
