### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by Calderon86** [OpenMediaVault-Plugin-Developers/docs#16]
Hi,

I am a complete rookie and was doing the OMV project for the Pi and I am having the following issue:
 -**502 bad gateway nginx  when  accessing to OMV via webbrowser**

I ve followed the steps provided on the following link: https://github.com/OpenMediaVault-Plugin-Developers/docs/blob/master/Adden-B-Installing_OMV5_on_an%20R-PI.pdf

So far everything has worked as expected and detailed in the document, but when it comes to configure OMV by accessing to the IP address of the PI  via the browser  (Point 10 of the manual)  I am prompted with the message 502 bad gateway nginx 

Details:
-I am using  a Pi 3b+ and a  32gb micro SD card
-The PI is connected via ethernet to the router
-Through PuTTY I can access to the PI  on that same IP Address.
-My browser is Edge. I have tried clearing cache and cookies and using private mode.
-I have restarted the PI checked the IP address and tried using that IP address on the browser (It did not change from the one I had originally) same outcome.
-I have tried doing it twice following the manual, both times with the same outcome.

I wonder if there is anything I am missing or I need to do.

Should you require any further information, please let me know.

Thank you in advance for your help,
Regards,

**Comment by votdev** [comment]
Please check `/var/log/nginx/openmediavault-webgui_error.log` for any error messages that may help to identify the problem.

**Comment by Calderon86** [comment]
Hi Votdev,
Thanks for your quick reply ,  when trying that I get a permission denied. I tried Sudo su /var/log/nginx/openmediavault-webgui_error.log and it says it does not exist
