### ISSUE TITLE
Filesystem Read-only while installing OMV

### ISSUE THREAD

**Issue by oliverhildner** [OpenMediaVault-Plugin-Developers/docs#17]
Hi, so when I try to install OMV on my rockpro64 I do exactly as the guide tells me. I enter the wget-command and the installation is running fine for around 10minutes.
Last lines before error (translated from german):
```
salt-common (3001.1+ds-1) setting up ....
dpkg: fatal error, abort
Status of  salt-common can't be synchronised: Input-/Outputerror
[  496.009348 EXT4-fs error (device mmcb1k0p1): ext4_journal_check_start:56: Detected aborted journal
[  496.032915 EXT4-fs (mmcb1k0p1) : Remounting filesystem read-only
E: Sub-process /usr/bin/dpkg returned an error code (2)
W: Problem when unlinking file /var/cache/apt/pkgcache.bin - pKgDPkgPM::Go (30: Filesystem read-only)
failed to install openmediavault package.
```

Any help would be really appreciated, thanks!

**Comment by ryecoaaron** [comment]
Sounds like your SD card is old/failing.

**Comment by oliverhildner** [comment]
It passed the test from H2testw. Was running like an hour. (32gb) But test was finished without an error.

**Comment by ryecoaaron** [comment]
That checks to make sure you have full capacity.  Is it a new card?

**Comment by oliverhildner** [comment]
yes the card is new. i bought it with the rockpro directly from the pinestore a few weeks ago.

**Comment by ryecoaaron** [comment]
Hmmm....  Can you post the rest of the install script log?  And check syslog messages.  A filesystem shouldn't go read only while installing packages.  Probably not much the install script do to help.  I have install on my rockpro64 many times without issues.

**Comment by oliverhildner** [comment]
Seems like the SD Card was trash. I am currenty installing it on another card I had lying around and it is running fine until now.
It surpassed the line where it failed the last times already.

**Comment by oliverhildner** [comment]
And the installation is complete. Thank you very much!
