### ISSUE TITLE
Does not boot after shutdown

### ISSUE THREAD

**Issue by oliverhildner** [OpenMediaVault-Plugin-Developers/docs#18]
Hello, 

so I had OMV Running for a few days now and everything is running fine. 
Today I shut down the device (rockpro64) with the shutdown command to relocate the nas.

After that It just won't boot after plugging it in. The disks are running but the fan won't start (wich indicates the system is booting). I then connected it directly to a monitor to see whats the problem but the monitor didn't show anything eiter. (No device found).
The device isn't visible in the network also.

After that I installed armbian on a fresh SD-Card, plugged it in an installed OMV. Rebooting is no problem. But once I type in "shutdown" in the command line the device won't boot anymore after reconnecting the power supply.

**Comment by ryecoaaron** [comment]
Which rockpro64 image are you using?  I can't think of anything that OMV does that would cause this.  This is most likely an Armbian issue that we can't fix.

**Comment by oliverhildner** [comment]
Thank you for your answer.
I don't know if it's a rockpro64 issue or a armbian issue but if I keep the power source disconnected for abour 15 minutes it works again. 
And as long as I don't pull out the power cable after shutdown it will start again when pressing the power button for about 5 seconds.
