### ISSUE TITLE
Errors on Odroid emmc module

### ISSUE THREAD

**Issue by Ubergeeksov** [OpenMediaVault-Plugin-Developers/docs#19]
Hi,

Firstly, thanks for these clear instructions. Unfortunately, I seem to be having a problem.

I have installed OMV5 following your instructions on a 16GB emmc module on an Odroid XU4. This was on Armbian Buster Server.

I can log into the GUI, but when I attempt to change password, I get an Error - Not Found. More details provide:

{"response":null,"error":{"code":0,"message":"The method 'setPassword' does not exist for the RPC service 'WebGui'.","trace":"OMV\\HttpErrorException: The method 'setPassword' does not exist for the RPC service 'WebGui'. in \/usr\/share\/php\/openmediavault\/rpc\/rpc.inc:91\nStack trace:\n#0 \/usr\/sbin\/omv-engined(537): OMV\\Rpc\\Rpc::call('WebGui', 'setPassword', Array, Array, 1)\n#1 {main}"}}

Similarly, if I try to add a DNS server address in network/interface settings I get an Error - Internal Server Error. More details provide:

{"response":null,"error":{"code":0,"message":"The property 'options' does not exist in the model 'conf.system.network.interface'.","trace":"OMV\\AssertException: The property 'options' does not exist in the model 'conf.system.network.interface'. in \/usr\/share\/php\/openmediavault\/config\/configobject.inc:71\nStack trace:\n#0 \/usr\/share\/php\/openmediavault\/config\/configobject.inc(187): OMV\\Config\\ConfigObject->assertExists('options')\n#1 \/usr\/share\/php\/openmediavault\/config\/configobject.inc(272): OMV\\Config\\ConfigObject->set('options', '', true)\n#2 \/usr\/share\/php\/openmediavault\/config\/configobject.inc(234): OMV\\Config\\ConfigObject->setFlatAssoc(Array, true, false)\n#3 \/usr\/share\/openmediavault\/engined\/rpc\/network.inc(143): OMV\\Config\\ConfigObject->setAssoc(Array)\n#4 \/usr\/share\/openmediavault\/engined\/rpc\/network.inc(547): Engined\\Rpc\\Network->setInterfaceConfig(Array, Array)\n#5 [internal function]: Engined\\Rpc\\Network->setEthernetIface(Array, Array)\n#6 \/usr\/share\/php\/openmediavault\/rpc\/serviceabstract.inc(123): call_user_func_array(Array, Array)\n#7 \/usr\/share\/php\/openmediavault\/rpc\/rpc.inc(86): OMV\\Rpc\\ServiceAbstract->callMethod('setEthernetIfac...', Array, Array)\n#8 \/usr\/sbin\/omv-engined(537): OMV\\Rpc\\Rpc::call('Network', 'setEthernetIfac...', Array, Array, 1)\n#9 {main}"}}

I also note that the System Information panel on the dashboard is blank.

This is a clean install, following the instructions to the letter.

Could the problem be that I am using an emmc module?

Thanks for any help.

Richard

**Comment by Ubergeeksov** [comment]
I should add, I also tried by first installing Armbian Buster Minimal, but with the same result.

**Comment by ryecoaaron** [comment]
Clear your browser cache.

**Comment by Ubergeeksov** [comment]
@ryecoaaron - Thank you so much. Problem solved.
