### ISSUE TITLE
Unsuccessful installation from Adden-A-Installing_OMV5_on_Armbian.pdf

### ISSUE THREAD

**Issue by linuxlifepage** [OpenMediaVault-Plugin-Developers/docs#23]
Hello!
I take image for my odroid from https://redirect.armbian.com/odroidxu4/Buster_legacy
And after I installation OMV for this tutorial Adden-A-Installing_OMV5_on_Armbian.pdf. 

And at the time of the netplan installation at the very end, it crashed with an error, since the script wrote an empty macaddress string to the network configuration, and the network service could not start. This is a bug in the script right?

[![2021-02-08-23-39-26.jpg](https://i.postimg.cc/N0QQgyYL/2021-02-08-23-39-26.jpg)](https://postimg.cc/v42JhZ4d)

**Comment by ryecoaaron** [comment]
The script is somewhat at fault but that is because you setup wireguard before installing OMV.  You should do all setup after running the install script.  I will have the script exclude wireguard interfaces.

**Comment by linuxlifepage** [comment]
Thank you!
