### ISSUE TITLE
No mention of Quicksync for Plex server

### ISSUE THREAD

**Issue by HannesJo0139** [OpenMediaVault-Plugin-Developers/docs#3]
First of all. Great guide!
I noticed that it is explained that transcoding e.g. via Plex requires a strong CPU. But it should at least be mentioned that Plex also supports hardware transcoding, especially via Quick Sync. Otherwise a beginner who wants to build a home media server could get the idea that a very expensive CPU is needed, although a small Intel Atom with Quicksync is sufficient.

**Comment by flmaxey** [comment]
Noted and added.
