### ISSUE TITLE
web version

### ISSUE THREAD

**Issue by rradar** [OpenMediaVault-Plugin-Developers/docs#5]
It's 2020 :tada:

**Comment by ryecoaaron** [comment]
Yep and what browser doesn't render PDFs as web page?

**Comment by rradar** [comment]
github is rendering the pdf's as images using the latest version of chrome which kills all links in the guide for example. And it's not responsive which makes it hardly usable with mobile devices...

I would even prefer to have that guide somewhere hidden in a forum instead of having it locked up in pdf's on github

**Comment by ryecoaaron** [comment]
It is "locked up" on github because the filesize is too large to attach to the forum.

**Comment by rradar** [comment]
![image](https://user-images.githubusercontent.com/34582688/75798230-31b5b880-5d6e-11ea-9378-87451d3cc527.png)

Over 1.5 million bytes for a file is too large to attach to a forum in 2020? :thinking:

**Comment by votdev** [comment]
> ![image](https://user-images.githubusercontent.com/34582688/75798230-31b5b880-5d6e-11ea-9378-87451d3cc527.png)
> 
> Over 1.5 million bytes for a file is too large to attach to a forum in 2020? thinking

It's no problem, but to keep the database small the size is limited. The problem is which size is the right one? A user with a 1.5MiB file says it's too less. So allowing up to 2MiB. The next one says i need 2.1MiB. ...

**Comment by ryecoaaron** [comment]
That one PDF might be ok but what about the others?  OMV is used by more than just Armbian/OMV 5 users.

**Comment by flmaxey** [comment]
> github is rendering the pdf's as images using the latest version of chrome which kills all links in the guide for example. And it's not responsive which makes it hardly usable with mobile devices...
_________________________________________________________

The instructions clearly state:
On the forum:
**To be able to copy and paste commands from these guides, and to use provided links, download the appropriate PDF and view it locally.**
On GitHub in **readme.md**:
**To use the links available in these documents and to enable copy & paste, download the PDF's and view them locally.**
Please note that I'm not trying to be insensitive as I ask this question;  is there some other way I could have made that more clear?  Perhaps something on the first page of all doc's?
________________________________________________________
The forum already has an enormous amount of data stored in it's thousands of threads, with picture and file attachments.  It's not the place to store large documents that need regular modification and are downloaded _frequently_.  If for no other reason, the bandwidth requirement would have an unnecessary performance impact.
