### ISSUE TITLE
OMV5 on Raspberry Pi instructions not allowing OMV installation 

### ISSUE THREAD

**Issue by Jesse-Reyes** [OpenMediaVault-Plugin-Developers/docs#7]
specifically running the highlighted command from the raspberry pi did not work as expected (No such file or directory) error. having to copy/paste the file via ftp then running dos2unix on the file to run with out errors.  

If you would like more details, let me know. 

![image](https://user-images.githubusercontent.com/18685018/76158124-517b1280-60c7-11ea-9d85-ec72d6a8f71f.png)

**Comment by ryecoaaron** [comment]
The script was created and edited in vi on Linux. Never on windows. So the line endings should never have to be changed. Are you sure the wget is able to download the script?

**Comment by IamDan77** [comment]
I too am having a problem installing

`pi@raspberrypi:~ $ wget -O - https://gitub.com/OpenMediaVault-Plugin-Developers/installScript/raw/master/install | sudo bash
--2020-03-31 06:26:07--  https://gitub.com/OpenMediaVault-Plugin-Developers/installScript/raw/master/install
Resolving gitub.com (gitub.com)... 104.200.23.95, 104.200.22.130
Connecting to gitub.com (gitub.com)|104.200.23.95|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: http://gitub.com/OpenMediaVault-Plugin-Developers/installScript/raw/master/install [following]
--2020-03-31 06:26:09--  http://gitub.com/OpenMediaVault-Plugin-Developers/installScript/raw/master/install
Connecting to gitub.com (gitub.com)|104.200.23.95|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 100 [application/octet-stream]
Saving to: ‘STDOUT’

-                                         100%[=====================================================================================>]     100  --.-KB/s    in 0s      

2020-03-31 06:26:09 (1.90 MB/s) - written to stdout [100/100]

bash: line 1: syntax error near unexpected token `<'
bash: line 1: `<html><head><title>gitub.com</title></head><body><h1>gitub.com</h1><p>Coming soon.</p></body></html>'
pi@raspberrypi:~ $ 
`
